### ISSUE TITLE
Sendings datas... OK but empty

### ISSUE THREAD

**Issue by daodevinc** [tuxity/betaseries-to-trakt#2]
Hi !

I have launch the script with all ID key and pin, script say OK in the end, but trakt.tv is always empty :/

2nd : 
It's possible to export/import the film with an another script ?

Thanks !

**Comment by tuxity** [comment]
Hi! Thanks for reporting it.

You know what? I'm gonna entirely check this script again, I don't like the way I've done it before :P 

I will let you know

**Comment by daodevinc** [comment]
Thanks !! :D 

(And they have surely changed method since, that will be the opportunity !)

**Comment by tuxity** [comment]
You can use the new script :)

I switch to python, movies are now handled and I build a Docker image now too!

Note: the watched date can't be synchronized, it's not present in the csv file, and neither in beteseries API it seems so i use the release date.

**Comment by daodevinc** [comment]
Ok thx !! :)
