### ISSUE TITLE
Erreur Python ?

### ISSUE THREAD

**Issue by daodevinc** [tuxity/betaseries-to-trakt#3]
Yop,

Autre bug avec le python (ou alors je ne sais pas faire).

Si je mets les ID, commande non reconnu, si je mets le python, le script ce lance mais erreur.

![pt](https://user-images.githubusercontent.com/9304947/29961986-b9043ad4-8f01-11e7-8925-f64023739927.png)

**Comment by tuxity** [comment]
Hmmm je sais pas comment ca fonctionne un script python sous windows :D Le terminal n'a pas l'air d'aimer les variables d'environnement mise avant le script.

Et pour la seconde erreur il faut faire`pip install -r requirements.txt`

**Comment by daodevinc** [comment]
Sous linux j'ai exactement la même erreur !
Il aime pas les variable avant le python, et si je mets pas les variables y'a une erreur.

**Comment by tuxity** [comment]
As-tu essayé de faire un export des variables avant de lancer le script avec python ? (sous unix)
```
export CLIENT_ID=
export CLIENT_SECRET=
```
(Un peu late la réponse)

**Comment by daodevinc** [comment]
Pas de soucis ^^
Qu'entends tu par export des variables ?
J'essaye demain

**Comment by billouetaudrey** [comment]
Bonjour, j'ai le même soucis, une solution ? J'ai tenter le export mais j'ai invalid syntax...

Il est pas possible d'inclure les ID et Secret + Fichiers csv dans le fichier Py ? ( j'y connais rien... )

Merci

**Comment by daodevinc** [comment]
Cool je croyais que ça venais de moi ! ^^
Comme le dit le dicton, c'était mieux avant x) enfin ça marchait quoi :p

**Comment by billouetaudrey** [comment]
Cool ? C'est sympa ça d'être content du malheur des autres :D

**Comment by urocreation** [comment]
Bonjour,
Un petit tuto pour faire fonctionner ce scrypt.
Installez Python3
Installez VsCode (ou tout autre IDE)
Dans un dossier téléchargez le fichier "betaseries-to-trakt.py"
L'ouvrir avec VsCode.
en dessous de la ligne 15 Ajouter 2 variable comme tel:
client_id = 'xxxxxxxxxxxxx'
client_secret = 'xxxxxxxxxxxxxx'
Remplacez les xxx ^^ mais laissez les quotes

le but ensuite est de remplacer toutes les occurences :
os.environ.get('CLIENT_ID') 
et 
os.environ.get('CLIENT_SECRET') 
par leur variables respectives.

A la ligne 24 surlignez ce code ci : os.environ.get('CLIENT_ID') 
Et faire click droit "change all occurence" et remplacer par client_id
faite de même a la ligne 38 : os.environ.get('CLIENT_SECRET') en remplacent Toutes les occurences par client_secret
Faite une recherche pour vous assurez qu'il ne reste AUCUNE occurrence  
Sauvegardez.

Dans le dossier ouvrez une invite de commande (dans la barre d'adresse de la fenêtre, taper cmd et faite entrée)
Pour finir lancez cette ligne de commande:
betaseries-to-trakt.py "C:/Users/xxx/Desktop/Séries de sdmuro.csv" "C:/Users/xxx/Desktop/Films de sdmuro.csv"
Attention au chemin d'accès de vos fichiers
Suivez les instructions
Il vous sera demandé de suivre un lien https (faire copier/coller/ dans votre navigateur et renseignez    le code pin obtenue)
ENJOY
