### ISSUE TITLE
0% watched on betaseries, 100% watched on trakt

### ISSUE THREAD

**Issue by raphodn** [tuxity/betaseries-to-trakt#4]
Hi !

I ran your script (without docker) to migrate my data from betaseries to trakt, but it seems that all the empty shows that I have on betaseries have been added as fully watched on betaseries.

More precisely:
- input file
```
id,thetvdb_id,title,archive,episode,remaining,status,tags
3764,250487,"American Horror Story",1,S00E00,84,0,
12819,309765,"Horace and Pete",0,S01E01,9,10,
```

- create_show() > print(show)
```
{'name': 'American Horror Story', 'ids': {'tvdb': '250487'}, 'watched_at': 'released', 'seasons': []}
{'name': 'Horace and Pete', 'ids': {'tvdb': '309765'}, 'watched_at': 'released', 'seasons': [{'number': 1, 'watched_at': 'released', 'episodes': [{'number': 1, 'watched_at': 'released'}]}]}
```

so the culprit might be the empty `'seasons': []` that is seen by trakt as 100% watched. I haven't looked at their api yet so not sure

Thanks !

PS: I'll continue digging a bit, can do a PR if I find anything useful :)

**Comment by raphodn** [comment]
ok so the API used here is [/sync/history](https://trakt.docs.apiary.io/#reference/sync/add-to-history/add-items-to-watched-history)

one idea could be that shows with a `status_pct === '0'` (or `obj[4] === 'S00E00'`) are processed separately and pushed to [/sync/watchlist](https://trakt.docs.apiary.io/#reference/sync/add-to-watchlist/add-items-to-watchlist) instead 😅

**Comment by tuxity** [comment]
Hi!

Good idea to add an `if()` on the `status_pct`, I haven't actualized this code since a while. And if I remember correctly, history and watchlist are 2 different functions on Trakt

**Comment by tuxity** [comment]
#5 merged :)
