### ISSUE TITLE
script doesn't seems to work with latest BetaSeries exports

### ISSUE THREAD

**Issue by MoOx** [tuxity/betaseries-to-trakt#7]
After running the script, here is what I got

```
Migration from Betaseries CSV files Done!

-----------------------------------------
HISTORY

Added:
	 0 episodes
	 0 movies

-----------------------------------------
WATCHLIST

Added:
	 0 shows
	 0 movies
```

**Comment by tuxity** [comment]
Hello!

I haven't worked on that in years, it might be deprecated. I can help you updating it if you need.

**Comment by MoOx** [comment]
I am trying to update it but it seems there isn't the necessary id to found the shows/movies since the CSV doesn't seems to have tmdb/tvdb ids...

Shows example

```
id,title,archive,episode,remaining,status,tags
27044,Ahsoka,0,S01E08,0,100,
27045,Andor,0,S01E22,0,100,
```

Movies example

```
id,title,status,date
122031,"Swamp Thing",0,
122023,"Supergirl: Woman of Tomorrow",0,
122030,"The Brave and the Bold",0,
```

**Comment by MoOx** [comment]
Am I wrong ?

**Comment by tuxity** [comment]
Yep, It doesn't looks ids from thetvdb.

https://www.betaseries.com/forum/questions/3841-csv-export-fields-pour-export-vers-trakt#p_292916

It seems you are not the only one. CSV export looks like a dead end (not cool, it was possible before). Maybe using the API?

**Comment by MisterDuval** [comment]
they removed imdb ID, so we can't import it to trakt.tv, this script isn't working anymore. The only ID we've got in the CSV is their internal ID.
The only solution I see should be to extract IMDB ID from their API:
https://developers.betaseries.com/reference/get-movies-movie
